dows:
  repository:
    workDir: C:\work\project\wes
    gitlab:
      #      username: lait
      #      password:
      host: http://192.168.23.19
      owner:
      #账号级别
      #      token: V878dXedjDCkv/TEUJJWc
      #org级别
      token:
    github:
      host: https://github.xxx.com
      owner: mindorg
      token: ${GITHUB_TOKEN}
