spring:
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      password:
      ttl: 3600  # 1 hour
      database: 1
  cache:
    type: caffeine
    cache-names:
      - userCache
    caffeine:
      spec: maximumSize=1024,refreshAfterWrite=60s